{
 "title": "Avalanche Main Dashboard",
 "description": "Home dashboard with most important indicators for your node and machine",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_weighted_average{job=\"avalanchego\"}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "gauge",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_rewarding_stake{job=\"avalanchego\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "X Chain Vertices",
   "type": "timeseries",
   "description": "Number of accepted and rejected vertices on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_X_vtx_rejected_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_P_blks_rejected_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_P_blks_built{job=\"avalanchego\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_health_checks_failing{job=\"avalanchego\"}"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time it takes to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_requests_average_latency"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of AVAX currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_total_staked{job=\"avalanchego\"}/1000000000",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_percent_connected{job=\"avalanchego\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_network_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_C_blks_rejected_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed C blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the C-Chain in the last day. Since C-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_built{job=\"avalanchego\"}[1d]))",
     "legendFormat": "Built C blocks"
    }
   ]
  },
  {
   "title": "Accepted Blocks/Vertices",
   "type": "bargauge",
   "description": "Number of blocks/vertices accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "bargauge",
   "description": "Number of blocks/vrtices currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_vtx_processing{job=\"avalanchego\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_blks_processing{job=\"avalanchego\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_blks_processing{job=\"avalanchego\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Number of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "X Chain"
    },
    {
     "expr": "(increase(avalanche_P_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_P_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_P_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "P Chain"
    },
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_db_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_db_get_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_db_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_db_has_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_db_compact_size_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_db_batch_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_db_batch_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_db_batch_reset_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_db_batch_replay_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}