{
 "title": "X-Chain",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Vertices Accepted/Rejected in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Vertex Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a vertex's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_X_vtx_accepted_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "rate(avalanche_X_vtx_rejected_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_X_vtx_rejected_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Vertices/Transactions Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_X_txs_processing{job=\"avalanchego\"}>0",
     "legendFormat": "Transactions"
    },
    {
     "expr": "avalanche_X_vtx_processing{job=\"avalanchego\"}>0",
     "legendFormat": "Vertices"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries sent that we receive a response to. (Average over the last 5 minutes.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[5m]) + 1) / (increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[5m]) + increase(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[5m]) + 1)",
     "legendFormat": "% Successful"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the X-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multiput_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_X_handler_app_response_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(avalanche_X_handler_app_gossip_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Message Handling Time",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the X-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_pull_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_push_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_chits_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multiput_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_multi_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_get_ancestors_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_get_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_get_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_get_ancestors_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_app_request_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_app_request_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_X_handler_app_gossip_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_app_gossip_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(avalanche_X_handler_app_response_sum{job=\"avalanchego\"}[5m])/rate(avalanche_X_handler_app_response_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(avalanche_X_benchlist_benched_weight{job=\"avalanchego\"}[15m]) / 10^9",
     "legendFormat": "AVAX Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the X-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multi_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_X_handler_app_request_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_X_handler_app_response_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(avalanche_X_handler_app_gossip_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "UTXO Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(avalanche_X_vm_utxo_cache_hit[5m])/(increase(avalanche_X_vm_utxo_cache_hit[5m])+increase(avalanche_X_vm_utxo_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_X_handler_unprocessed_msgs_len",
     "legendFormat": "Pending Messages"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(avalanche_X_handler_expired[1m])",
     "legendFormat": "Expired"
    }
   ]
  }
 ]
}